### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by TranceGeniK** [dvlpp/sharp#4]
Hi,

This project deosn't seem to be sleeping, but I can't find any up-to-date documentation :(
I managed to install it on laravel 5.3 but I am facing many errors regarding the config file. Can you please at least provide a new config file ?

Thanks!

**Comment by dvlpp** [comment]
Hi,

You are right, the project is far for sleeping, and is used on quite some online websites now, but we are very very _very_ late on the documentation. I plan to work on it before 2017...

One sure thing: everything changed since the last doc update. So my only advice, sadly, is to look for another solution for now, since it will be hard to understand the project without it.

I'm very sorry...
